#
#
# Cobblemon: Generation Spawning - A NeoForge Minecraft Mod.
#
# Copyright (c) 2026 DAN2026. All rights reserved.
#
# This software is licensed under the CobblemonGenerationSpawning License v1.0.
#  A copy of this License should have been included with this software.
#  If not, you can obtain a copy at [https://github.com/DAN2026/CobblemonGenerationSpawning/blob/master/LICENSE].
#

org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

#mod definitions
# TODO: You might want to change set of properties
archives_base_name=zian-generation-spawns
mod_version=1.2.0-alpha.2
maven_group=net.dan2026

#fabric project dependencies
fabric_loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1
fabric_kotlin=1.13.6+kotlin.2.2.20

#neoforge project dependencies
neoforge_version=21.1.182
kotlin_for_forge_version=5.10.0

#common dependencies
minecraft_version=1.21.1
cobblemon_version=1.8.1+1.21.1
junit_version=5.1.0

# architectury dependencies
architectury_version=13.0.6
